name: Deploy Antigravity Site

on:
  push:
    branches: ["main"] # Asegúrate de que tu rama se llame main

permissions:
  contents: read
  id-token: write   # Esto soluciona tu error
  pages: write      # Esto permite el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Sube todos los archivos que vemos en tu imagen

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
